In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("coffeeshopsales.csv")

In [3]:
df

,transaction_id,transaction_date,transaction_time,store_id,store_location,product_id,transaction_qty,unit_price,product_category,product_type,product_detail,Size,Total_bill,Month Name,Day Name,Hour,Day of Week,Month
0,114301,6/1/2023,11:33:29 AM,3,Astoria,45,1,3.00,Tea,Brewed herbal tea,Peppermint,Large,3.0,June,Thursday,11,4,6
1,115405,6/2/2023,11:18:24 AM,3,Astoria,45,1,3.00,Tea,Brewed herbal tea,Peppermint,Large,3.0,June,Friday,11,5,6
2,115478,6/2/2023,12:02:45 PM,3,Astoria,45,1,3.00,Tea,Brewed herbal tea,Peppermint,Large,3.0,June,Friday,12,5,6
3,116288,6/2/2023,7:39:47 PM,3,Astoria,45,1,3.00,Tea,Brewed herbal tea,Peppermint,Large,3.0,June,Friday,19,5,6
4,116714,6/3/2023,12:24:57 PM,3,Astoria,45,1,3.00,Tea,Brewed herbal tea,Peppermint,Large,3.0,June,Saturday,12,6,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149111,129465,6/14/2023,8:34:10 AM,5,Lower Manhattan,41,4,4.25,Coffee,Barista Espresso,Cappuccino,Large,17.0,June,Wednesday,8,3,6
149112,133523,6/17/2023,9:55:47 AM,8,Hell's Kitchen,8,8,45.00,Coffee beans,Premium Beans,Civet Cat,Not Defined,360.0,June,Saturday,9,6,6
149113,133674,6/17/2023,10:41:11 AM,8,Hell's Kitchen,8,8,45.00,Coffee beans,Premium Beans,Civet Cat,Not Defined,360.0,June,Saturday,10,6,6
149114,133744,6/17/2023,11:18:31 AM,8,Hell's Kitchen,8,8,45.00,Coffee beans,Premium Beans,Civet Cat,Not Defined,360.0,June,Saturday,11,6,6
149115,149043,6/30/2023,11:18:31 AM,8,Hell's Kitchen,8,8,45.00,Coffee beans,Premium Beans,Civet Cat,Not Defined,360.0,June,Friday,11,5,6

In [4]:
df2=df.head(10000)

In [5]:
df2

,transaction_id,transaction_date,transaction_time,store_id,store_location,product_id,transaction_qty,unit_price,product_category,product_type,product_detail,Size,Total_bill,Month Name,Day Name,Hour,Day of Week,Month
0,114301,6/1/2023,11:33:29 AM,3,Astoria,45,1,3.0,Tea,Brewed herbal tea,Peppermint,Large,3.0,June,Thursday,11,4,6
1,115405,6/2/2023,11:18:24 AM,3,Astoria,45,1,3.0,Tea,Brewed herbal tea,Peppermint,Large,3.0,June,Friday,11,5,6
2,115478,6/2/2023,12:02:45 PM,3,Astoria,45,1,3.0,Tea,Brewed herbal tea,Peppermint,Large,3.0,June,Friday,12,5,6
3,116288,6/2/2023,7:39:47 PM,3,Astoria,45,1,3.0,Tea,Brewed herbal tea,Peppermint,Large,3.0,June,Friday,19,5,6
4,116714,6/3/2023,12:24:57 PM,3,Astoria,45,1,3.0,Tea,Brewed herbal tea,Peppermint,Large,3.0,June,Saturday,12,6,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,23226,2/11/2023,8:55:32 AM,3,Astoria,26,1,3.0,Coffee,Organic brewed coffee,Brazilian,Regular,3.0,February,Saturday,8,6,2
9996,23430,2/11/2023,1:26:51 PM,3,Astoria,26,1,3.0,Coffee,Organic brewed coffee,Brazilian,Regular,3.0,February,Saturday,13,6,2
9997,24593,2/13/2023,12:19:33 PM,3,Astoria,26,1,3.0,Coffee,Organic brewed coffee,Brazilian,Regular,3.0,February,Monday,12,1,2
9998,24645,2/13/2023,2:24:33 PM,3,Astoria,26,1,3.0,Coffee,Organic brewed coffee,Brazilian,Regular,3.0,February,Monday,14,1,2
9999,24850,2/14/2023,8:23:42 AM,3,Astoria,26,1,3.0,Coffee,Organic brewed coffee,Brazilian,Regular,3.0,February,Tuesday,8,2,2

In [6]:
df2

,transaction_id,transaction_date,transaction_time,store_id,store_location,product_id,transaction_qty,unit_price,product_category,product_type,product_detail,Size,Total_bill,Month Name,Day Name,Hour,Day of Week,Month
0,114301,6/1/2023,11:33:29 AM,3,Astoria,45,1,3.0,Tea,Brewed herbal tea,Peppermint,Large,3.0,June,Thursday,11,4,6
1,115405,6/2/2023,11:18:24 AM,3,Astoria,45,1,3.0,Tea,Brewed herbal tea,Peppermint,Large,3.0,June,Friday,11,5,6
2,115478,6/2/2023,12:02:45 PM,3,Astoria,45,1,3.0,Tea,Brewed herbal tea,Peppermint,Large,3.0,June,Friday,12,5,6
3,116288,6/2/2023,7:39:47 PM,3,Astoria,45,1,3.0,Tea,Brewed herbal tea,Peppermint,Large,3.0,June,Friday,19,5,6
4,116714,6/3/2023,12:24:57 PM,3,Astoria,45,1,3.0,Tea,Brewed herbal tea,Peppermint,Large,3.0,June,Saturday,12,6,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,23226,2/11/2023,8:55:32 AM,3,Astoria,26,1,3.0,Coffee,Organic brewed coffee,Brazilian,Regular,3.0,February,Saturday,8,6,2
9996,23430,2/11/2023,1:26:51 PM,3,Astoria,26,1,3.0,Coffee,Organic brewed coffee,Brazilian,Regular,3.0,February,Saturday,13,6,2
9997,24593,2/13/2023,12:19:33 PM,3,Astoria,26,1,3.0,Coffee,Organic brewed coffee,Brazilian,Regular,3.0,February,Monday,12,1,2
9998,24645,2/13/2023,2:24:33 PM,3,Astoria,26,1,3.0,Coffee,Organic brewed coffee,Brazilian,Regular,3.0,February,Monday,14,1,2
9999,24850,2/14/2023,8:23:42 AM,3,Astoria,26,1,3.0,Coffee,Organic brewed coffee,Brazilian,Regular,3.0,February,Tuesday,8,2,2

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 149116 entries, 0 to 149115
Data columns (total 18 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   transaction_id    149116 non-null  int64
 1   transaction_date  149116 non-null  str
 2   transaction_time  149116 non-null  str
 3   store_id          149116 non-null  int64
 4   store_location    149116 non-null  str
 5   product_id        149116 non-null  int64
 6   transaction_qty   149116 non-null  int64
 7   unit_price        149116 non-null  float64
 8   product_category  149116 non-null  str
 9   product_type      149116 non-null  str
 10  product_detail    149116 non-null  str
 11  Size              149116 non-null  str
 12  Total_bill        149116 non-null  float64
 13  Month Name        149116 non-null  str
 14  Day Name          149116 non-null  str
 15  Hour              149116 non-null  int64
 16  Day of Week       149116 non-null  int64
 17  Month             149116 non-null  int64
dtypes: float64(2), int64(7), str(9)
memory usage: 32.9 MB

In [8]:
df2 = df.drop("Month", axis='columns')

In [9]:
df2

,transaction_id,transaction_date,transaction_time,store_id,store_location,product_id,transaction_qty,unit_price,product_category,product_type,product_detail,Size,Total_bill,Month Name,Day Name,Hour,Day of Week
0,114301,6/1/2023,11:33:29 AM,3,Astoria,45,1,3.00,Tea,Brewed herbal tea,Peppermint,Large,3.0,June,Thursday,11,4
1,115405,6/2/2023,11:18:24 AM,3,Astoria,45,1,3.00,Tea,Brewed herbal tea,Peppermint,Large,3.0,June,Friday,11,5
2,115478,6/2/2023,12:02:45 PM,3,Astoria,45,1,3.00,Tea,Brewed herbal tea,Peppermint,Large,3.0,June,Friday,12,5
3,116288,6/2/2023,7:39:47 PM,3,Astoria,45,1,3.00,Tea,Brewed herbal tea,Peppermint,Large,3.0,June,Friday,19,5
4,116714,6/3/2023,12:24:57 PM,3,Astoria,45,1,3.00,Tea,Brewed herbal tea,Peppermint,Large,3.0,June,Saturday,12,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149111,129465,6/14/2023,8:34:10 AM,5,Lower Manhattan,41,4,4.25,Coffee,Barista Espresso,Cappuccino,Large,17.0,June,Wednesday,8,3
149112,133523,6/17/2023,9:55:47 AM,8,Hell's Kitchen,8,8,45.00,Coffee beans,Premium Beans,Civet Cat,Not Defined,360.0,June,Saturday,9,6
149113,133674,6/17/2023,10:41:11 AM,8,Hell's Kitchen,8,8,45.00,Coffee beans,Premium Beans,Civet Cat,Not Defined,360.0,June,Saturday,10,6
149114,133744,6/17/2023,11:18:31 AM,8,Hell's Kitchen,8,8,45.00,Coffee beans,Premium Beans,Civet Cat,Not Defined,360.0,June,Saturday,11,6
149115,149043,6/30/2023,11:18:31 AM,8,Hell's Kitchen,8,8,45.00,Coffee beans,Premium Beans,Civet Cat,Not Defined,360.0,June,Friday,11,5

In [10]:
df2

,transaction_id,transaction_date,transaction_time,store_id,store_location,product_id,transaction_qty,unit_price,product_category,product_type,product_detail,Size,Total_bill,Month Name,Day Name,Hour,Day of Week
0,114301,6/1/2023,11:33:29 AM,3,Astoria,45,1,3.00,Tea,Brewed herbal tea,Peppermint,Large,3.0,June,Thursday,11,4
1,115405,6/2/2023,11:18:24 AM,3,Astoria,45,1,3.00,Tea,Brewed herbal tea,Peppermint,Large,3.0,June,Friday,11,5
2,115478,6/2/2023,12:02:45 PM,3,Astoria,45,1,3.00,Tea,Brewed herbal tea,Peppermint,Large,3.0,June,Friday,12,5
3,116288,6/2/2023,7:39:47 PM,3,Astoria,45,1,3.00,Tea,Brewed herbal tea,Peppermint,Large,3.0,June,Friday,19,5
4,116714,6/3/2023,12:24:57 PM,3,Astoria,45,1,3.00,Tea,Brewed herbal tea,Peppermint,Large,3.0,June,Saturday,12,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149111,129465,6/14/2023,8:34:10 AM,5,Lower Manhattan,41,4,4.25,Coffee,Barista Espresso,Cappuccino,Large,17.0,June,Wednesday,8,3
149112,133523,6/17/2023,9:55:47 AM,8,Hell's Kitchen,8,8,45.00,Coffee beans,Premium Beans,Civet Cat,Not Defined,360.0,June,Saturday,9,6
149113,133674,6/17/2023,10:41:11 AM,8,Hell's Kitchen,8,8,45.00,Coffee beans,Premium Beans,Civet Cat,Not Defined,360.0,June,Saturday,10,6
149114,133744,6/17/2023,11:18:31 AM,8,Hell's Kitchen,8,8,45.00,Coffee beans,Premium Beans,Civet Cat,Not Defined,360.0,June,Saturday,11,6
149115,149043,6/30/2023,11:18:31 AM,8,Hell's Kitchen,8,8,45.00,Coffee beans,Premium Beans,Civet Cat,Not Defined,360.0,June,Friday,11,5

In [11]:
df2=df.head(10000)

In [12]:
df2

,transaction_id,transaction_date,transaction_time,store_id,store_location,product_id,transaction_qty,unit_price,product_category,product_type,product_detail,Size,Total_bill,Month Name,Day Name,Hour,Day of Week,Month
0,114301,6/1/2023,11:33:29 AM,3,Astoria,45,1,3.0,Tea,Brewed herbal tea,Peppermint,Large,3.0,June,Thursday,11,4,6
1,115405,6/2/2023,11:18:24 AM,3,Astoria,45,1,3.0,Tea,Brewed herbal tea,Peppermint,Large,3.0,June,Friday,11,5,6
2,115478,6/2/2023,12:02:45 PM,3,Astoria,45,1,3.0,Tea,Brewed herbal tea,Peppermint,Large,3.0,June,Friday,12,5,6
3,116288,6/2/2023,7:39:47 PM,3,Astoria,45,1,3.0,Tea,Brewed herbal tea,Peppermint,Large,3.0,June,Friday,19,5,6
4,116714,6/3/2023,12:24:57 PM,3,Astoria,45,1,3.0,Tea,Brewed herbal tea,Peppermint,Large,3.0,June,Saturday,12,6,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,23226,2/11/2023,8:55:32 AM,3,Astoria,26,1,3.0,Coffee,Organic brewed coffee,Brazilian,Regular,3.0,February,Saturday,8,6,2
9996,23430,2/11/2023,1:26:51 PM,3,Astoria,26,1,3.0,Coffee,Organic brewed coffee,Brazilian,Regular,3.0,February,Saturday,13,6,2
9997,24593,2/13/2023,12:19:33 PM,3,Astoria,26,1,3.0,Coffee,Organic brewed coffee,Brazilian,Regular,3.0,February,Monday,12,1,2
9998,24645,2/13/2023,2:24:33 PM,3,Astoria,26,1,3.0,Coffee,Organic brewed coffee,Brazilian,Regular,3.0,February,Monday,14,1,2
9999,24850,2/14/2023,8:23:42 AM,3,Astoria,26,1,3.0,Coffee,Organic brewed coffee,Brazilian,Regular,3.0,February,Tuesday,8,2,2

In [13]:
df2

,transaction_id,transaction_date,transaction_time,store_id,store_location,product_id,transaction_qty,unit_price,product_category,product_type,product_detail,Size,Total_bill,Month Name,Day Name,Hour,Day of Week,Month
0,114301,6/1/2023,11:33:29 AM,3,Astoria,45,1,3.0,Tea,Brewed herbal tea,Peppermint,Large,3.0,June,Thursday,11,4,6
1,115405,6/2/2023,11:18:24 AM,3,Astoria,45,1,3.0,Tea,Brewed herbal tea,Peppermint,Large,3.0,June,Friday,11,5,6
2,115478,6/2/2023,12:02:45 PM,3,Astoria,45,1,3.0,Tea,Brewed herbal tea,Peppermint,Large,3.0,June,Friday,12,5,6
3,116288,6/2/2023,7:39:47 PM,3,Astoria,45,1,3.0,Tea,Brewed herbal tea,Peppermint,Large,3.0,June,Friday,19,5,6
4,116714,6/3/2023,12:24:57 PM,3,Astoria,45,1,3.0,Tea,Brewed herbal tea,Peppermint,Large,3.0,June,Saturday,12,6,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,23226,2/11/2023,8:55:32 AM,3,Astoria,26,1,3.0,Coffee,Organic brewed coffee,Brazilian,Regular,3.0,February,Saturday,8,6,2
9996,23430,2/11/2023,1:26:51 PM,3,Astoria,26,1,3.0,Coffee,Organic brewed coffee,Brazilian,Regular,3.0,February,Saturday,13,6,2
9997,24593,2/13/2023,12:19:33 PM,3,Astoria,26,1,3.0,Coffee,Organic brewed coffee,Brazilian,Regular,3.0,February,Monday,12,1,2
9998,24645,2/13/2023,2:24:33 PM,3,Astoria,26,1,3.0,Coffee,Organic brewed coffee,Brazilian,Regular,3.0,February,Monday,14,1,2
9999,24850,2/14/2023,8:23:42 AM,3,Astoria,26,1,3.0,Coffee,Organic brewed coffee,Brazilian,Regular,3.0,February,Tuesday,8,2,2

In [14]:
df2 = df.drop("Month", axis='columns')

In [15]:
df2

,transaction_id,transaction_date,transaction_time,store_id,store_location,product_id,transaction_qty,unit_price,product_category,product_type,product_detail,Size,Total_bill,Month Name,Day Name,Hour,Day of Week
0,114301,6/1/2023,11:33:29 AM,3,Astoria,45,1,3.00,Tea,Brewed herbal tea,Peppermint,Large,3.0,June,Thursday,11,4
1,115405,6/2/2023,11:18:24 AM,3,Astoria,45,1,3.00,Tea,Brewed herbal tea,Peppermint,Large,3.0,June,Friday,11,5
2,115478,6/2/2023,12:02:45 PM,3,Astoria,45,1,3.00,Tea,Brewed herbal tea,Peppermint,Large,3.0,June,Friday,12,5
3,116288,6/2/2023,7:39:47 PM,3,Astoria,45,1,3.00,Tea,Brewed herbal tea,Peppermint,Large,3.0,June,Friday,19,5
4,116714,6/3/2023,12:24:57 PM,3,Astoria,45,1,3.00,Tea,Brewed herbal tea,Peppermint,Large,3.0,June,Saturday,12,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149111,129465,6/14/2023,8:34:10 AM,5,Lower Manhattan,41,4,4.25,Coffee,Barista Espresso,Cappuccino,Large,17.0,June,Wednesday,8,3
149112,133523,6/17/2023,9:55:47 AM,8,Hell's Kitchen,8,8,45.00,Coffee beans,Premium Beans,Civet Cat,Not Defined,360.0,June,Saturday,9,6
149113,133674,6/17/2023,10:41:11 AM,8,Hell's Kitchen,8,8,45.00,Coffee beans,Premium Beans,Civet Cat,Not Defined,360.0,June,Saturday,10,6
149114,133744,6/17/2023,11:18:31 AM,8,Hell's Kitchen,8,8,45.00,Coffee beans,Premium Beans,Civet Cat,Not Defined,360.0,June,Saturday,11,6
149115,149043,6/30/2023,11:18:31 AM,8,Hell's Kitchen,8,8,45.00,Coffee beans,Premium Beans,Civet Cat,Not Defined,360.0,June,Friday,11,5